# Generated by Django 3.1.1 on 2021-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.IntegerField(choices=[(0, 'En espera'), (1, 'Aceptado'), (2, 'Rechazado'), (3, 'Error')], default=0),
        ),
    ]
